name: Rice Intelligence Daily Automated Run

on:
  schedule:
    # รันอัตโนมัติทุกวัน เวลา 08:00 น. (เวลาไทย)
    - cron: '0 1 * * *'
  workflow_dispatch:

jobs:
  run-rice-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
         pip install google-genai gspread oauth2client requests beautifulsoup4


      - name: Run Rice Intelligence Engine
        run: python app.py

